# https://rust-lang.github.io/mdBook/

[book]
title = "libreelec-repacker"
description = "Declaratively customize and repack official LibreELEC disk images without rebuilding from source."
authors = ["Takumi Takahashi"]
src = "docs"
language = "ja"
multilingual = false

[build]
build-dir = "book"
create-missing = false

[output.html]
git-repository-url = "https://github.com/takumin/libreelec-repacker"
